### ISSUE TITLE
Automatic bid

### ISSUE THREAD

**Issue by facenord-sud** [ase-15/ebay#13]
Do an automatic bid when a bid is created.

Use the method after_create in the Bid model

Only one automatic bid by auction otherwise recursivity problems?

**Comment by tibm** [comment]
I'm not sure I understand this issue. Ok for the CREATION of the AutomaticBid, BUT, why use a method after_create? Because one may want to add an AutomaticBid or not. This has no direct link with the Bid... right? 

Further on: no! Only one AutomaticBid by USER. no recursive problems... Or am I missing something here?

**Comment by facenord-sud** [comment]
I did something I leave you see in commit 787ab265da14e92b82e7a41d83fd74dc2ee905c3

**Comment by tibm** [comment]
I update it, but need to go, you may see my idea. I'll fix it tonight. Missing:
new_amount as param and stop-condition (ignore self + ignore if over max_amount)
See commit https://github.com/ase-15/ebay/commit/b0c8d7405d7a7126cefc841f78cbc3815cb32072

**Comment by tibm** [comment]
Please test, on my last commit: https://github.com/ase-15/ebay/commit/5ceca02123691addef41354c328419dc166163cc
I think it's working. Worth testing and debugging if necessary
